apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  values:
    fullnameOverride: external-dns
    provider: aws
    txtOwnerId: projectx-cluster-dev
    domainFilters:
      - bootaeva.com
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::570082719665:role/projectx-cluster-dev-external-dns-role
    env:
      - name: AWS_REGION
        value: us-east-1